import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

/**
 * Writes `environment.production.ts` from environment variables just before a
 * production build.
 *
 * The admin portal path has to reach the browser — the Angular router needs it to
 * know the route exists — so it is in the bundle no matter what. What it must not be
 * is committed: this repository is public, and a value sitting in git is greppable
 * without anyone even visiting the site. Injecting it at build time keeps the
 * checked-in file a placeholder while the deployed bundle carries the real one.
 *
 * Run automatically by `npm run build` (see the prebuild script). With no variables
 * set it writes the placeholders back, so a local build is a no-op.
 */

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, '../src/environments/environment.production.ts');

const apiBase = process.env['API_BASE'] ?? '/api';
const adminPortalPath = process.env['ADMIN_PORTAL_PATH'] ?? 'CHANGE-ME-BEFORE-DEPLOY';

if (adminPortalPath === 'CHANGE-ME-BEFORE-DEPLOY') {
  console.warn(
    '[env] ADMIN_PORTAL_PATH is not set — building with the placeholder. The server ' +
      'refuses to start in production with this value, which is the intended guard.',
  );
}

const contents = `// Generated by scripts/write-env.mjs at build time. Do not edit by hand —
// set API_BASE and ADMIN_PORTAL_PATH in the build environment instead.
export const environment = {
  production: true,
  apiBase: ${JSON.stringify(apiBase)},
  adminPortalPath: ${JSON.stringify(adminPortalPath)},
};
`;

writeFileSync(target, contents);
console.log(`[env] wrote environment.production.ts — apiBase ${apiBase}`);
