// Generated by scripts/write-env.mjs at build time. Do not edit by hand —
// set API_BASE and ADMIN_PORTAL_PATH in the build environment instead.
export const environment = {
  production: true,
  apiBase: "/api",
  adminPortalPath: "CHANGE-ME-BEFORE-DEPLOY",
};
